import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// styles
import "./globals.css";
import { ThemeProvider } from "next-themes";
// import styles from "@/styles/index";

// redux
import StoreProvider from "./StoreProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
      >
        <StoreProvider>
          <ThemeProvider attribute="class">
            <main className="flex flex-col gap-8 row-start-2 items-center min-h-screen w-full">
              {children}
            </main>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
